/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compiler;

import compiler.session;
import compiler.session;

/**
 *
 * @author Rahul
 */
public class BitsInterface extends javax.swing.JFrame {

    session S;
    ProblemClass[] P = new ProblemClass[5];
    
    
    public BitsInterface(session S1) {
        initComponents();
        S = S1;
        for(int i=0; i<P.length;i++){
            System.out.println(i);
            P[i] = new ProblemClass();
            P[i].addProblem(i,S1);
            
        }
        setProblems();
    }
        
        BitsInterface(){
        initComponents();
    }

    

    private void setProblems(){
        
        problemStatementTextArea.setText(P[0].getTitle());
        problemStatementTextArea.setEditable(false);
        problemStatementTextArea1.setText(P[1].getTitle());
        problemStatementTextArea1.setEditable(false);
        problemStatementTextArea2.setText(P[2].getTitle());
        problemStatementTextArea2.setEditable(false);
        problemStatementTextArea3.setText(P[3].getTitle());
        problemStatementTextArea3.setEditable(false);
        problemStatementTextArea4.setText(P[4].getTitle());
        problemStatementTextArea4.setEditable(false);
        
    }
  
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basePanel = new javax.swing.JPanel();
        rankButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        teamNameLabel = new javax.swing.JLabel();
        timerLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        problemStatementPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        problemStatementTextArea = new javax.swing.JTextArea();
        P1Button = new javax.swing.JButton();
        problemStatementPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        problemStatementTextArea1 = new javax.swing.JTextArea();
        P2Button = new javax.swing.JButton();
        problemStatementPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        problemStatementTextArea2 = new javax.swing.JTextArea();
        P3Button = new javax.swing.JButton();
        problemStatementPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        problemStatementTextArea3 = new javax.swing.JTextArea();
        P4Button = new javax.swing.JButton();
        problemStatementPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        problemStatementTextArea4 = new javax.swing.JTextArea();
        P0Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        optionsMenu = new javax.swing.JMenu();
        exitMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        basePanel.setPreferredSize(new java.awt.Dimension(1366, 768));
        basePanel.setLayout(null);

        rankButton.setFont(new java.awt.Font("Tekton Pro", 0, 20)); // NOI18N
        rankButton.setForeground(new java.awt.Color(255, 255, 255));
        rankButton.setText("Rank");
        rankButton.setBorder(null);
        rankButton.setContentAreaFilled(false);
        rankButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankButtonActionPerformed(evt);
            }
        });
        basePanel.add(rankButton);
        rankButton.setBounds(78, 548, 154, 29);

        refreshButton.setFont(new java.awt.Font("Tekton Pro", 0, 20)); // NOI18N
        refreshButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshButton.setText("Refresh");
        refreshButton.setContentAreaFilled(false);
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        basePanel.add(refreshButton);
        refreshButton.setBounds(78, 600, 154, 29);

        teamNameLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        teamNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        basePanel.add(teamNameLabel);
        teamNameLabel.setBounds(50, 130, 210, 50);

        timerLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        timerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        basePanel.add(timerLabel);
        timerLabel.setBounds(50, 195, 210, 50);

        statusLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        basePanel.add(statusLabel);
        statusLabel.setBounds(62, 270, 187, 229);

        problemStatementPanel.setBackground(new java.awt.Color(255, 255, 255));

        problemStatementTextArea.setColumns(20);
        problemStatementTextArea.setRows(5);
        jScrollPane1.setViewportView(problemStatementTextArea);

        javax.swing.GroupLayout problemStatementPanelLayout = new javax.swing.GroupLayout(problemStatementPanel);
        problemStatementPanel.setLayout(problemStatementPanelLayout);
        problemStatementPanelLayout.setHorizontalGroup(
            problemStatementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        problemStatementPanelLayout.setVerticalGroup(
            problemStatementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        basePanel.add(problemStatementPanel);
        problemStatementPanel.setBounds(387, 90, 820, 100);

        P1Button.setText("...");
        P1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1ButtonActionPerformed(evt);
            }
        });
        basePanel.add(P1Button);
        P1Button.setBounds(1233, 235, 40, 40);

        problemStatementPanel1.setBackground(new java.awt.Color(255, 255, 255));

        problemStatementTextArea1.setColumns(20);
        problemStatementTextArea1.setRows(5);
        jScrollPane2.setViewportView(problemStatementTextArea1);

        javax.swing.GroupLayout problemStatementPanel1Layout = new javax.swing.GroupLayout(problemStatementPanel1);
        problemStatementPanel1.setLayout(problemStatementPanel1Layout);
        problemStatementPanel1Layout.setHorizontalGroup(
            problemStatementPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        problemStatementPanel1Layout.setVerticalGroup(
            problemStatementPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        basePanel.add(problemStatementPanel1);
        problemStatementPanel1.setBounds(387, 204, 820, 100);

        P2Button.setText("...");
        P2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P2ButtonActionPerformed(evt);
            }
        });
        basePanel.add(P2Button);
        P2Button.setBounds(1233, 346, 40, 40);

        problemStatementPanel2.setBackground(new java.awt.Color(255, 255, 255));

        problemStatementTextArea2.setColumns(20);
        problemStatementTextArea2.setRows(5);
        jScrollPane3.setViewportView(problemStatementTextArea2);

        javax.swing.GroupLayout problemStatementPanel2Layout = new javax.swing.GroupLayout(problemStatementPanel2);
        problemStatementPanel2.setLayout(problemStatementPanel2Layout);
        problemStatementPanel2Layout.setHorizontalGroup(
            problemStatementPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        problemStatementPanel2Layout.setVerticalGroup(
            problemStatementPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        basePanel.add(problemStatementPanel2);
        problemStatementPanel2.setBounds(387, 318, 820, 100);

        P3Button.setText("...");
        P3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P3ButtonActionPerformed(evt);
            }
        });
        basePanel.add(P3Button);
        P3Button.setBounds(1233, 460, 40, 40);

        problemStatementPanel3.setBackground(new java.awt.Color(255, 255, 255));

        problemStatementTextArea3.setColumns(20);
        problemStatementTextArea3.setRows(5);
        jScrollPane4.setViewportView(problemStatementTextArea3);

        javax.swing.GroupLayout problemStatementPanel3Layout = new javax.swing.GroupLayout(problemStatementPanel3);
        problemStatementPanel3.setLayout(problemStatementPanel3Layout);
        problemStatementPanel3Layout.setHorizontalGroup(
            problemStatementPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        problemStatementPanel3Layout.setVerticalGroup(
            problemStatementPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        basePanel.add(problemStatementPanel3);
        problemStatementPanel3.setBounds(387, 432, 820, 100);

        P4Button.setText("...");
        P4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P4ButtonActionPerformed(evt);
            }
        });
        basePanel.add(P4Button);
        P4Button.setBounds(1233, 577, 40, 40);

        problemStatementPanel4.setBackground(new java.awt.Color(255, 255, 255));

        problemStatementTextArea4.setColumns(20);
        problemStatementTextArea4.setRows(5);
        jScrollPane5.setViewportView(problemStatementTextArea4);

        javax.swing.GroupLayout problemStatementPanel4Layout = new javax.swing.GroupLayout(problemStatementPanel4);
        problemStatementPanel4.setLayout(problemStatementPanel4Layout);
        problemStatementPanel4Layout.setHorizontalGroup(
            problemStatementPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        problemStatementPanel4Layout.setVerticalGroup(
            problemStatementPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        basePanel.add(problemStatementPanel4);
        problemStatementPanel4.setBounds(387, 546, 820, 100);

        P0Button.setText("...");
        P0Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P0ButtonActionPerformed(evt);
            }
        });
        basePanel.add(P0Button);
        P0Button.setBounds(1233, 120, 40, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compiler/images/Home Screen.jpg"))); // NOI18N
        basePanel.add(jLabel1);
        jLabel1.setBounds(0, 0, 1390, 700);

        optionsMenu.setText("Options");
        jMenuBar1.add(optionsMenu);

        exitMenu.setText("Exit");
        jMenuBar1.add(exitMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(basePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(basePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rankButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rankButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void P0ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P0ButtonActionPerformed
        // TODO add your handling code here:
        Problem pr = new Problem(S,P[0]);
        pr.setLocation(0, 0);
        pr.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P0ButtonActionPerformed

    private void P1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1ButtonActionPerformed
        // TODO add your handling code here:
        Problem pr = new Problem(S,P[1]);
        pr.setLocation(0, 0);
        pr.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P1ButtonActionPerformed

    private void P2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P2ButtonActionPerformed
        // TODO add your handling code here:
        Problem pr = new Problem(S,P[2]);
        pr.setLocation(0, 0);
        pr.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P2ButtonActionPerformed

    private void P3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P3ButtonActionPerformed
        // TODO add your handling code here:
        Problem pr = new Problem(S,P[3]);
        pr.setLocation(0, 0);
        pr.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P3ButtonActionPerformed

    private void P4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P4ButtonActionPerformed
        // TODO add your handling code here:
        Problem pr = new Problem(S,P[4]);
        pr.setLocation(0, 0);
        pr.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P4ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BitsInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BitsInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BitsInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BitsInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BitsInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton P0Button;
    private javax.swing.JButton P1Button;
    private javax.swing.JButton P2Button;
    private javax.swing.JButton P3Button;
    private javax.swing.JButton P4Button;
    private javax.swing.JPanel basePanel;
    private javax.swing.JMenu exitMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JMenu optionsMenu;
    private javax.swing.JPanel problemStatementPanel;
    private javax.swing.JPanel problemStatementPanel1;
    private javax.swing.JPanel problemStatementPanel2;
    private javax.swing.JPanel problemStatementPanel3;
    private javax.swing.JPanel problemStatementPanel4;
    private javax.swing.JTextArea problemStatementTextArea;
    private javax.swing.JTextArea problemStatementTextArea1;
    private javax.swing.JTextArea problemStatementTextArea2;
    private javax.swing.JTextArea problemStatementTextArea3;
    private javax.swing.JTextArea problemStatementTextArea4;
    private javax.swing.JButton rankButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel teamNameLabel;
    private javax.swing.JLabel timerLabel;
    // End of variables declaration//GEN-END:variables
}
